// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
import "quasar/docs/types/feature-flag";

declare module "quasar/docs/types/feature-flag" {
  interface QuasarFeatureFlags {
    pwa: true;
  }
}
